version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - hertzg
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    reviewers:
      - hertzg
    versioning-strategy: increase-if-necessary
