name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        node: # https://nodejs.org/en/about/releases/
          - "14.x" # Active LTS
          - "12.x" # Active LTS
          - "10.x" # Maintenance LTS
      fail-fast: false
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: npm run test
