name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        node: # https://nodejs.org/en/about/releases/
          - "20.x"
          - "19.x"
          - "18.x"
      fail-fast: false
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: npm run test
