name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        node: # https://nodejs.org/en/about/releases/
          - "14" # Active LTS
          - "12" # Active LTS
          - "10" # Maintenance LTS
      fail-fast: false

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: "14.x"
      - uses: bahmutov/npm-install@v1
      - run: npm run test

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'hertzg/node-gdate-julian' }}
    steps:
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: "14.x"
      - uses: bahmutov/npm-install@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
